baseURL = 'https://enochyu.com/'
title = 'Enoch Yu'
defaultContentLanguage = 'en'

enableRobotsTXT = true

[params]
author = "Enoch Yu"
favicon = "/img/favicon/favicon.ico"
  [params.social]
    youtube = "https://www.youtube.com/@enochyu_official"
    github = "https://github.com/enochyu-official"
    blog = "https://blog.enochyu.com/"
    archive = "https://archive.enochyu.com/"

[security]
  allowContent = ['^text/html$']

